"""Python client for the ai-heeczer ingestion service (plan 0006)."""

from .client import (
    ApiErrorKind,
    ConfidenceBand,
    Event,
    EventContext,
    EventIdentity,
    EventMeta,
    EventMetrics,
    EventTask,
    HeeczerApiError,
    HeeczerClient,
    HeeczerUnsupportedModeError,
    IngestEventResponse,
    Mode,
    Outcome,
    RetryPolicy,
    RiskClass,
    ScoreResult,
    SyncHeeczerClient,
    VersionResponse,
)
from .models import (
    EventContextModel,
    EventIdentityModel,
    EventMetaModel,
    EventMetricsModel,
    EventModel,
    EventTaskModel,
    validate_event,
)

__all__ = [
    "ApiErrorKind",
    "ConfidenceBand",
    "Event",
    "EventContext",
    "EventIdentity",
    "EventMeta",
    "EventMetrics",
    "EventTask",
    "HeeczerApiError",
    "HeeczerClient",
    "HeeczerUnsupportedModeError",
    "IngestEventResponse",
    "Mode",
    "Outcome",
    "RiskClass",
    "RetryPolicy",
    "ScoreResult",
    "SyncHeeczerClient",
    "VersionResponse",
    "EventContextModel",
    "EventIdentityModel",
    "EventMetaModel",
    "EventMetricsModel",
    "EventModel",
    "EventTaskModel",
    "validate_event",
]

__version__ = "0.5.1"
