/* Generated by cbindgen. Do not edit manually. */
/* cbindgen:autogen_warning */

#ifndef HEECZER_CORE_C_H
#define HEECZER_CORE_C_H

#include <stdint.h>
#include <stdlib.h>

/**
 * Free a string previously returned by this library. Passing a null pointer is a no-op.
 */
void heeczer_free_string(char *s);

/**
 * Score an event. All arguments are NUL-terminated UTF-8 JSON strings.
 *
 * `profile_json` and `tiers_json` may be NULL to use the embedded defaults.
 * `tier_override` may be NULL.
 *
 * Returns a NUL-terminated JSON envelope:
 *   `{"ok": true, "result": <ScoreResult>}` on success
 *   `{"ok": false, "error": "..."}` on failure
 *
 * The returned pointer must be released via `heeczer_free_string`.
 */
char *heeczer_score_json(const char *event_json,
                          const char *profile_json,
                          const char *tiers_json,
                          const char *tier_override);

/**
 * Return a JSON object with the library versions:
 * `{"scoring_version": "...", "spec_version": "...", "crate_version": "..."}`
 *
 * The returned pointer must be released via `heeczer_free_string`.
 */
char *heeczer_versions_json(void);

#endif /* HEECZER_CORE_C_H */
